[package]
name = "gamu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13.2"
bevy_editor_pls = "0.8.1"
bevy_rapier3d = "0.26.0"
bevy_xpbd_3d = "0.4.2"
env_logger = "0.11.3"
log = "0.4.21"
